### ISSUE TITLE
resurrection epic

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#292]
Discussed wtih @pared, that unfortunately, dvc-bench is not operational for quite some time now. There has been multiple things that have put final nails in its coffin (like the introduction of a few more long-running tests), and so now we need to perform some rituals to dig it up from the grave, resurrect it and hopefully make it more robust, so it doesn't die on us the next time we can't babysit it.

- [ ] unify workflows for master/pr/nightly #291
- [ ] parallelize tests across machines #281
- [ ] consider weekly builds for the chunkiest tests/datasets
- [ ] create creature comforts like env detection, --enable-s3/etc that we have in dvc tests, so that this test suit could be ran locally without headache
- [ ] migrate to pytest-benchmark? #286

**Comment by pared** [comment]
We need also to recreate a functionality pinging us about regressions.

**Comment by efiop** [comment]
For the record: regressions are discussed in https://github.com/iterative/dvc-bench/issues/294
